services:
  postgres:
    image: postgres:15-alpine
    container_name: login-postgres
    environment:
      POSTGRES_DB: login_db
      POSTGRES_USER: login_user
      POSTGRES_PASSWORD: login_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U login_user -d login_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  login-app:
    build:
      context: .
      dockerfile: Dockerfile  # ← Usa o multistage acima
    container_name: login-spring-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: docker-super-secret-key-for-development-only-256-bits-long
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/login_db
      SPRING_DATASOURCE_USERNAME: login_user
      SPRING_DATASOURCE_PASSWORD: login_pass
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: